create table HYGIENE 
(SHOPNAME VARCHAR2(15),
 SECTOR VARCHAR2(10),
 LOC VARCHAR2(20),
 BUSINESS_LICENSE NUMBER(10),
 VIOLATION_DETAILS VARCHAR2(10),
 CONSTRAINT HYGIENE_BL_PK PRIMARY kEY("BUSINESS_LICENSE")) 
 
 CREATE TABLE REVIEW 
 (ID VARCHAR2 (10),
 REVIEW VARCHAR2(30),
 RATING NUMBER (1),
 REPLY VARCHAR2(30),
 CONSTRAINT REVIEW_ID_PK PRIMARY KEY ("ID"))
 
 CREATE TABLE RIDER 
 (ID VARCHAR2 (10),
 PW VARCHAR2(15),
 RIDERNAME VARCHAR2(5),
 RATING NUMBER(1),
 TRANSPORTATION VARCHAR2(10),
 LOC VARCHAR2(5),
 COMPANY VARCHAR2 (10),
 CONSTRAINT RIDER_ID_PK PRIMARY KEY( "ID"))
 
 CREATE TABLE SHOPKEEPER 
 (ID VARCHAR2 (10),
 PW VARCHAR2 (15),
 SHOPNAME VARCHAR2 (10),
 ADDRESS VARCHAR2(20),
BUSINESS_LICENSE VARCHAR2 (10),
RATING NUMBER(1),
TEL NUMBER(11),
CONSTRAINT SHOPKEEPER_ID_PK PRIMARY KEY( "ID"),
CONSTRAINT SHOPKEPPER_BUSINESS_LICENSE_UK UNIQUE("BUSINESS_LICENSE")
 )
 
 CREATE TABLE USER 
 (ID VARCHAR2 (10),
 PW VARCHAR2 (15),
 USERNAME VARCHAR2 (5),
 ADDRESS VARCHAR2(20),
 PHONE NUMBER (11),
 CONSTRAINT USER_ID_PK PRIMARY KEY( "ID"),
 CONSTRAINT USER_PHONE_UK UNIQUE ("PHONE")
 )
 
 CREATE TABLE ID 
 (ID VARCHAR2 (10),
 CONSTRAINT USER_ID_PK PRIMARY KEY( "ID")
 )
 
 
 